/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherReviewRouteImport } from './routes/teacher-review'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as ExamsExamIdTakeRouteImport } from './routes/exams.$examId.take'
import { Route as ExamsExamIdResultsRouteImport } from './routes/exams.$examId.results'
import { Route as ExamsExamIdMyResultRouteImport } from './routes/exams.$examId.my-result'
import { Route as CoursesCourseIdExamsNewRouteImport } from './routes/courses.$courseId.exams.new'

const TeacherReviewRoute = TeacherReviewRouteImport.update({
  id: '/teacher-review',
  path: '/teacher-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdTakeRoute = ExamsExamIdTakeRouteImport.update({
  id: '/exams/$examId/take',
  path: '/exams/$examId/take',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdResultsRoute = ExamsExamIdResultsRouteImport.update({
  id: '/exams/$examId/results',
  path: '/exams/$examId/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdMyResultRoute = ExamsExamIdMyResultRouteImport.update({
  id: '/exams/$examId/my-result',
  path: '/exams/$examId/my-result',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdExamsNewRoute = CoursesCourseIdExamsNewRouteImport.update({
  id: '/exams/new',
  path: '/exams/new',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/teacher-review': typeof TeacherReviewRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/exams/$examId/my-result': typeof ExamsExamIdMyResultRoute
  '/exams/$examId/results': typeof ExamsExamIdResultsRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
  '/courses/$courseId/exams/new': typeof CoursesCourseIdExamsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/teacher-review': typeof TeacherReviewRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/exams/$examId/my-result': typeof ExamsExamIdMyResultRoute
  '/exams/$examId/results': typeof ExamsExamIdResultsRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
  '/courses/$courseId/exams/new': typeof CoursesCourseIdExamsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/teacher-review': typeof TeacherReviewRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/exams/$examId/my-result': typeof ExamsExamIdMyResultRoute
  '/exams/$examId/results': typeof ExamsExamIdResultsRoute
  '/exams/$examId/take': typeof ExamsExamIdTakeRoute
  '/courses/$courseId/exams/new': typeof CoursesCourseIdExamsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/teacher-review'
    | '/courses/$courseId'
    | '/exams/$examId/my-result'
    | '/exams/$examId/results'
    | '/exams/$examId/take'
    | '/courses/$courseId/exams/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/teacher-review'
    | '/courses/$courseId'
    | '/exams/$examId/my-result'
    | '/exams/$examId/results'
    | '/exams/$examId/take'
    | '/courses/$courseId/exams/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/teacher-review'
    | '/courses/$courseId'
    | '/exams/$examId/my-result'
    | '/exams/$examId/results'
    | '/exams/$examId/take'
    | '/courses/$courseId/exams/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  TeacherReviewRoute: typeof TeacherReviewRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
  ExamsExamIdMyResultRoute: typeof ExamsExamIdMyResultRoute
  ExamsExamIdResultsRoute: typeof ExamsExamIdResultsRoute
  ExamsExamIdTakeRoute: typeof ExamsExamIdTakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher-review': {
      id: '/teacher-review'
      path: '/teacher-review'
      fullPath: '/teacher-review'
      preLoaderRoute: typeof TeacherReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/take': {
      id: '/exams/$examId/take'
      path: '/exams/$examId/take'
      fullPath: '/exams/$examId/take'
      preLoaderRoute: typeof ExamsExamIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/results': {
      id: '/exams/$examId/results'
      path: '/exams/$examId/results'
      fullPath: '/exams/$examId/results'
      preLoaderRoute: typeof ExamsExamIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/my-result': {
      id: '/exams/$examId/my-result'
      path: '/exams/$examId/my-result'
      fullPath: '/exams/$examId/my-result'
      preLoaderRoute: typeof ExamsExamIdMyResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/exams/new': {
      id: '/courses/$courseId/exams/new'
      path: '/exams/new'
      fullPath: '/courses/$courseId/exams/new'
      preLoaderRoute: typeof CoursesCourseIdExamsNewRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
  }
}

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdExamsNewRoute: typeof CoursesCourseIdExamsNewRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdExamsNewRoute: CoursesCourseIdExamsNewRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  TeacherReviewRoute: TeacherReviewRoute,
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
  ExamsExamIdMyResultRoute: ExamsExamIdMyResultRoute,
  ExamsExamIdResultsRoute: ExamsExamIdResultsRoute,
  ExamsExamIdTakeRoute: ExamsExamIdTakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
